"use client";

import { useMemo, useState, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import type { DataTableRow, TrendFilter } from "@/components/data-table";
import { cn } from "@/lib/utils";

type SignalTone = "positive" | "negative" | "neutral";

type MovementSignal = {
  id: string;
  icon: string;
  tone: SignalTone;
  text: string;
  caption: string;
};

type WinCandidate = {
  reason: string;
  query: string;
  clicksGrowth: number;
  positionFrom?: number;
  positionTo?: number;
  score: number;
};

function buildShareCaption(siteName: string, signal: MovementSignal): string {
  return `${signal.text}\n\nTracking powered by Consoleview.\n${siteName}`;
}

function makeShareImage(siteName: string, signal: MovementSignal): string {
  const canvas = document.createElement("canvas");
  canvas.width = 1200;
  canvas.height = 630;
  const ctx = canvas.getContext("2d");
  if (!ctx) return "";

  ctx.fillStyle = "#0f172a";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = "#e2e8f0";
  ctx.font = "700 52px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText("SEO Win", 80, 120);

  ctx.fillStyle = "#93c5fd";
  ctx.font = "600 34px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText(siteName, 80, 178);

  ctx.fillStyle = "#f8fafc";
  ctx.font = "600 40px system-ui, -apple-system, Segoe UI, sans-serif";
  const text = signal.text.length > 84 ? `${signal.text.slice(0, 81)}...` : signal.text;
  ctx.fillText(text, 80, 290);

  ctx.fillStyle = "#34d399";
  ctx.font = "600 30px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText("Generated by Consoleview", 80, 540);

  return canvas.toDataURL("image/png");
}

function maybeCopyCaption(caption: string) {
  if (!navigator.clipboard?.writeText) return;
  navigator.clipboard.writeText(caption).catch(() => {
    // ignore clipboard errors; sharing/export can still proceed
  });
}

function toDelta(value: number | undefined): string {
  const safe = value ?? 0;
  return `${safe >= 0 ? "+" : ""}${safe}%`;
}

function detectBestWin(
  queriesRows: DataTableRow[],
  newQueriesRows: DataTableRow[],
  querySparklines: Record<string, number[]>
): WinCandidate | null {
  const candidates: WinCandidate[] = [];

  const clickGrowth = [...queriesRows]
    .filter((r) => r.changePercent != null)
    .sort((a, b) => (b.changePercent ?? 0) - (a.changePercent ?? 0))[0];
  if (clickGrowth?.changePercent != null) {
    candidates.push({
      reason: "Largest click growth",
      query: clickGrowth.key,
      clicksGrowth: clickGrowth.changePercent,
      positionTo: clickGrowth.position,
      score: clickGrowth.changePercent,
    });
  }

  const top3New = [...newQueriesRows]
    .filter((r) => r.position != null && r.position <= 3)
    .sort((a, b) => (a.position ?? 99) - (b.position ?? 99))[0];
  if (top3New) {
    candidates.push({
      reason: "New top 3 ranking",
      query: top3New.key,
      clicksGrowth: top3New.changePercent ?? 0,
      positionTo: top3New.position,
      score: 120 + (top3New.changePercent ?? 0),
    });
  }

  const impressionJump = [...queriesRows]
    .filter((r) => (r.changePercent ?? 0) > 0)
    .sort((a, b) => b.impressions - a.impressions)[0];
  if (impressionJump) {
    candidates.push({
      reason: "Large impression jump",
      query: impressionJump.key,
      clicksGrowth: impressionJump.changePercent ?? 0,
      positionTo: impressionJump.position,
      score: Math.min(140, impressionJump.impressions / 50),
    });
  }

  const biggestPositionJump = Object.entries(querySparklines)
    .map(([query, positions]) => {
      const first = positions[0];
      const last = positions[positions.length - 1];
      if (first == null || last == null) return null;
      const jump = first - last;
      if (jump <= 0) return null;
      const row = queriesRows.find((r) => r.key === query);
      return {
        query,
        first,
        last,
        jump,
        changePercent: row?.changePercent ?? 0,
      };
    })
    .filter((x): x is NonNullable<typeof x> => x != null)
    .sort((a, b) => b.jump - a.jump)[0];
  if (biggestPositionJump) {
    candidates.push({
      reason: "Biggest position jump",
      query: biggestPositionJump.query,
      clicksGrowth: biggestPositionJump.changePercent,
      positionFrom: biggestPositionJump.first,
      positionTo: biggestPositionJump.last,
      score: 100 + biggestPositionJump.jump * 5,
    });
  }

  if (candidates.length === 0) return null;
  return [...candidates].sort((a, b) => b.score - a.score)[0];
}

async function fetchAiSummary(signals: { direction: string; sentence: string }[], propertyId?: string) {
  const res = await fetch("/api/ai/movement-summary", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ signals, propertyId }),
  });
  if (!res.ok) return null;
  const data = await res.json();
  return data.summary as string | null;
}

function toneClass(tone: SignalTone): string {
  return tone === "positive"
    ? "text-positive"
    : tone === "negative"
      ? "text-negative"
      : "text-muted-foreground";
}

function applyTrendFilter(signals: MovementSignal[], trendFilter: TrendFilter): MovementSignal[] {
  if (trendFilter === "all") return signals;
  if (trendFilter === "growing") return signals.filter((s) => s.tone === "positive");
  if (trendFilter === "decaying" || trendFilter === "lost") return signals.filter((s) => s.tone === "negative");
  if (trendFilter === "new") return signals.filter((s) => s.id === "new-ranking" || s.id === "content-win");
  return signals;
}

function IconAction({
  label,
  title,
  onClick,
  children,
}: {
  label: string;
  title: string;
  onClick: () => void;
  children: ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="inline-flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground"
      aria-label={label}
      title={title}
    >
      {children}
    </button>
  );
}

export function MovementIntelligence({
  queriesRows,
  pagesRows,
  newQueriesRows = [],
  querySparklines = {},
  siteName,
  trendFilter,
  onTrendFilterChange,
  propertyId,
}: {
  queriesRows: DataTableRow[];
  pagesRows: DataTableRow[];
  newQueriesRows?: DataTableRow[];
  querySparklines?: Record<string, number[]>;
  siteName: string;
  trendFilter: TrendFilter;
  onTrendFilterChange: (t: TrendFilter) => void;
  propertyId?: string;
}) {
  const [actionHint, setActionHint] = useState<string | null>(null);

  const topGrowingQuery = useMemo(
    () =>
      [...queriesRows]
        .filter((r) => (r.changePercent ?? 0) > 0)
        .sort((a, b) => (b.changePercent ?? 0) - (a.changePercent ?? 0))[0],
    [queriesRows]
  );

  const topDecayingQuery = useMemo(
    () =>
      [...queriesRows]
        .filter((r) => (r.changePercent ?? 0) < 0)
        .sort((a, b) => (a.changePercent ?? 0) - (b.changePercent ?? 0))[0],
    [queriesRows]
  );

  const newTop10Page = useMemo(
    () =>
      [...pagesRows]
        .filter((r) => r.position != null && r.position <= 10 && (r.changePercent ?? 0) > 0)
        .sort((a, b) => (a.position ?? 99) - (b.position ?? 99))[0],
    [pagesRows]
  );

  const rankingDrop = useMemo(
    () =>
      [...queriesRows]
        .filter((r) => r.position != null && r.position >= 12 && (r.changePercent ?? 0) < 0)
        .sort((a, b) => (b.position ?? 0) - (a.position ?? 0))[0],
    [queriesRows]
  );

  const signals = useMemo<MovementSignal[]>(() => {
    const out: MovementSignal[] = [];

    if (topGrowingQuery) {
      out.push({
        id: "rising-query",
        icon: "↑",
        tone: "positive",
        text: `Query "${topGrowingQuery.key}" gained ${toDelta(topGrowingQuery.changePercent)} clicks`,
        caption: `We've just improved "${topGrowingQuery.key}" by ${toDelta(topGrowingQuery.changePercent)} clicks this period.`,
      });
    }

    if (topDecayingQuery) {
      out.push({
        id: "lost-traffic",
        icon: "↓",
        tone: "negative",
        text: `Query "${topDecayingQuery.key}" lost ${Math.abs(topDecayingQuery.changePercent ?? 0)}% clicks`,
        caption: `We're addressing a drop on "${topDecayingQuery.key}" (${Math.abs(topDecayingQuery.changePercent ?? 0)}% clicks).`,
      });
    }

    if (newTop10Page) {
      out.push({
        id: "new-ranking",
        icon: "✨",
        tone: "positive",
        text: `Page "${newTop10Page.key}" entered top 10`,
        caption: `New ranking win: "${newTop10Page.key}" entered the top 10.`,
      });
    }

    if (rankingDrop) {
      out.push({
        id: "ranking-drop",
        icon: "⚠",
        tone: "negative",
        text: `Query "${rankingDrop.key}" dropped to pos ${rankingDrop.position?.toFixed(1)}`,
        caption: `Monitoring ranking volatility: "${rankingDrop.key}" is now at position ${rankingDrop.position?.toFixed(1)}.`,
      });
    }

    const contentWin = [...pagesRows]
      .filter((r) => (r.changePercent ?? 0) > 0)
      .sort((a, b) => b.impressions - a.impressions)[0];
    if (contentWin) {
      out.push({
        id: "content-win",
        icon: "✨",
        tone: "neutral",
        text: `Content win: "${contentWin.key}" gained ${contentWin.impressions.toLocaleString()} impressions`,
        caption: `Content momentum: "${contentWin.key}" gained ${contentWin.impressions.toLocaleString()} impressions.`,
      });
    }

    const filtered = applyTrendFilter(out, trendFilter).slice(0, 5);
    if (filtered.length > 0) return filtered;
    return [
      {
        id: "empty",
        icon: "ℹ",
        tone: "neutral",
        text: "No ranking signals detected in this range",
        caption: "No ranking signals detected in this range.",
      },
    ];
  }, [topGrowingQuery, topDecayingQuery, newTop10Page, rankingDrop, pagesRows, trendFilter]);

  const bestWin = useMemo(
    () => detectBestWin(queriesRows, newQueriesRows, querySparklines),
    [queriesRows, newQueriesRows, querySparklines]
  );

  const signalsKey = useMemo(
    () => signals.map((s) => s.text).join("|"),
    [signals]
  );

  const { data: aiSummary, isLoading: aiLoading } = useQuery({
    queryKey: ["ai-movement-summary", propertyId, signalsKey],
    queryFn: () =>
      fetchAiSummary(
        signals.map((s) => ({
          direction: s.tone === "negative" ? "decaying" : "growing",
          sentence: s.text,
        })),
        propertyId
      ),
    enabled: signals.length > 0 && signals[0].id !== "empty",
    staleTime: 5 * 60 * 1000,
    refetchOnWindowFocus: false,
  });

  const handleExport = async (signal: MovementSignal) => {
    const mergedSignal: MovementSignal = {
      ...signal,
      caption: `${signal.caption}\n\nTracking powered by Consoleview.`,
    };
    const caption = buildShareCaption(siteName, mergedSignal);
    maybeCopyCaption(caption);
    const image = makeShareImage(siteName, signal);
    if (!image) return;
    const blob = await (await fetch(image)).blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "seo-insight.png";
    a.click();
    URL.revokeObjectURL(url);
    setActionHint("Image exported and caption copied");
  };

  const handleShare = async (signal: MovementSignal) => {
    const mergedSignal: MovementSignal = {
      ...signal,
      caption: `${signal.caption}\n\nTracking powered by Consoleview.`,
    };
    const caption = buildShareCaption(siteName, mergedSignal);
    maybeCopyCaption(caption);
    const image = makeShareImage(siteName, signal);
    if (!image) return;
    const blob = await (await fetch(image)).blob();
    const file = new File([blob], "seo-insight.png", { type: "image/png" });

    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({
        title: "SEO Insight",
        text: caption,
        files: [file],
      });
      setActionHint("Shared successfully");
      return;
    }

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "seo-insight.png";
    a.click();
    URL.revokeObjectURL(url);
    setActionHint("Image downloaded and caption copied");
  };

  return (
    <section
      aria-label="Movement intelligence"
      className="rounded-lg border border-border bg-surface overflow-hidden transition-colors duration-[120ms] hover:border-foreground/20 shadow-[0_2px_8px_rgba(0,0,0,0.05)]"
    >
      <div className="flex items-center justify-between border-b border-border px-4 py-2.5">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-semibold text-foreground">Movement intelligence</h2>
            {bestWin && (
              <span className="rounded-full border border-border px-2 py-0.5 text-[11px] text-muted-foreground">
                🏆 SEO win available
              </span>
            )}
          </div>
          <p className="text-xs text-muted-foreground mt-0.5">
            Short ranking signals for the selected period
          </p>
        </div>
        <div className="flex gap-0.5 rounded-md border border-input bg-background p-0.5">
          {(["all", "growing", "decaying", "new", "lost"] as const).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => onTrendFilterChange(t)}
              className={cn(
                "rounded px-2 py-1 text-xs font-medium capitalize transition-colors duration-[120ms]",
                trendFilter === t
                  ? "bg-background text-foreground border border-input"
                  : "text-muted-foreground hover:bg-accent"
              )}
            >
              {t}
            </button>
          ))}
        </div>
      </div>

      <div className="px-4 py-2.5 space-y-1.5 border-b border-border/50">
        {signals.map((signal) => (
          <div key={signal.id} className="flex items-start justify-between gap-2">
            <div className="min-w-0 flex items-start gap-2 text-sm">
              <span className={cn("mt-px shrink-0 text-xs", toneClass(signal.tone))}>{signal.icon}</span>
              <span className="truncate text-foreground">{signal.text}</span>
            </div>
            {signal.id !== "empty" && (
              <div className="flex shrink-0 items-center gap-1">
                <IconAction
                  label="Export this insight"
                  title="Export this insight image"
                  onClick={() => void handleExport(signal)}
                >
                  <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                </IconAction>
                <IconAction
                  label="Share this insight"
                  title="Share this insight"
                  onClick={() => void handleShare(signal)}
                >
                  <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden>
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C9.112 12.325 10.13 11.6 11.316 11.6c1.186 0 2.204.725 2.632 1.742M18 8.5a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zM8 18.5a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zM20 18.5a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zM8.684 15.658l6.632 2.684M15.316 5.658L8.684 8.342" />
                  </svg>
                </IconAction>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="px-4 py-2 border-t border-border/40">
        {actionHint && (
          <p className="text-[11px] text-muted-foreground mb-1">{actionHint}.</p>
        )}
        <p className="text-[11px] text-muted-foreground uppercase tracking-wide mb-1 font-medium">AI summary</p>
        {aiLoading ? (
          <p className="text-xs text-muted-foreground/70 italic">Generating insight...</p>
        ) : aiSummary ? (
          <p className="text-xs text-muted-foreground">{aiSummary}</p>
        ) : (
          <p className="text-xs text-muted-foreground/70 italic">
            {signals.length === 0 || signals[0].id === "empty"
              ? "No movement signals to analyse."
              : "AI summary unavailable."}
          </p>
        )}
      </div>
    </section>
  );
}
