"use client";

import { useMemo } from "react";
import type { DataTableRow } from "@/components/data-table";
import { DashboardCard } from "@/components/ui/dashboard-card";

type Confidence = "High" | "Medium" | "Low";

type WinCandidate = {
  reason: string;
  query: string;
  clicksGrowth: number;
  positionFrom?: number;
  positionTo?: number;
  confidence: Confidence;
  score: number;
};

export interface ShareSeoWinCardProps {
  siteName: string;
  queriesRows: DataTableRow[];
  newQueriesRows?: DataTableRow[];
  querySparklines?: Record<string, number[]>;
}

function confidenceLabel(impressions: number, clicksGrowth: number): Confidence {
  if (impressions >= 2500 && Math.abs(clicksGrowth) >= 60) return "High";
  if (impressions >= 1000 && Math.abs(clicksGrowth) >= 25) return "Medium";
  return "Low";
}

function makeShareImage(siteName: string, win: WinCandidate): string {
  const canvas = document.createElement("canvas");
  canvas.width = 1200;
  canvas.height = 630;
  const ctx = canvas.getContext("2d");
  if (!ctx) return "";

  ctx.fillStyle = "#0f172a";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.fillStyle = "#e2e8f0";
  ctx.font = "700 52px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText("SEO Win", 80, 120);

  ctx.fillStyle = "#93c5fd";
  ctx.font = "600 34px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText(siteName, 80, 178);

  ctx.fillStyle = "#f8fafc";
  ctx.font = "600 40px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText(`"${win.query}"`, 80, 290);

  ctx.fillStyle = "#34d399";
  ctx.font = "600 34px system-ui, -apple-system, Segoe UI, sans-serif";
  if (win.positionFrom != null && win.positionTo != null) {
    ctx.fillText(`Position ${win.positionFrom.toFixed(1)} → ${win.positionTo.toFixed(1)}`, 80, 360);
  }
  ctx.fillText(`${win.clicksGrowth >= 0 ? "+" : ""}${win.clicksGrowth}% clicks`, 80, 420);

  ctx.fillStyle = "#94a3b8";
  ctx.font = "500 24px system-ui, -apple-system, Segoe UI, sans-serif";
  ctx.fillText("Generated by Consoleview", 80, 540);

  return canvas.toDataURL("image/png");
}

export function ShareSeoWinCard({
  siteName,
  queriesRows,
  newQueriesRows = [],
  querySparklines = {},
}: ShareSeoWinCardProps) {
  const bestWin = useMemo<WinCandidate | null>(() => {
    const candidates: WinCandidate[] = [];

    const clickGrowth = [...queriesRows]
      .filter((r) => r.changePercent != null)
      .sort((a, b) => (b.changePercent ?? 0) - (a.changePercent ?? 0))[0];
    if (clickGrowth?.changePercent != null) {
      candidates.push({
        reason: "Largest click growth",
        query: clickGrowth.key,
        clicksGrowth: clickGrowth.changePercent,
        positionTo: clickGrowth.position,
        confidence: confidenceLabel(clickGrowth.impressions, clickGrowth.changePercent),
        score: clickGrowth.changePercent,
      });
    }

    const top3New = [...newQueriesRows]
      .filter((r) => r.position != null && r.position <= 3)
      .sort((a, b) => (a.position ?? 99) - (b.position ?? 99))[0];
    if (top3New) {
      candidates.push({
        reason: "New top 3 ranking",
        query: top3New.key,
        clicksGrowth: top3New.changePercent ?? 0,
        positionTo: top3New.position,
        confidence: confidenceLabel(top3New.impressions, top3New.changePercent ?? 0),
        score: 120 + (top3New.changePercent ?? 0),
      });
    }

    const impressionJump = [...queriesRows]
      .filter((r) => (r.changePercent ?? 0) > 0)
      .sort((a, b) => b.impressions - a.impressions)[0];
    if (impressionJump) {
      candidates.push({
        reason: "Large impression jump",
        query: impressionJump.key,
        clicksGrowth: impressionJump.changePercent ?? 0,
        positionTo: impressionJump.position,
        confidence: confidenceLabel(impressionJump.impressions, impressionJump.changePercent ?? 0),
        score: Math.min(140, impressionJump.impressions / 50),
      });
    }

    const biggestPositionJump = Object.entries(querySparklines)
      .map(([query, positions]) => {
        const first = positions[0];
        const last = positions[positions.length - 1];
        if (first == null || last == null) return null;
        const jump = first - last;
        if (jump <= 0) return null;
        const row = queriesRows.find((r) => r.key === query);
        return {
          query,
          first,
          last,
          jump,
          changePercent: row?.changePercent ?? 0,
          impressions: row?.impressions ?? 0,
        };
      })
      .filter((x): x is NonNullable<typeof x> => x != null)
      .sort((a, b) => b.jump - a.jump)[0];
    if (biggestPositionJump) {
      candidates.push({
        reason: "Biggest position jump",
        query: biggestPositionJump.query,
        clicksGrowth: biggestPositionJump.changePercent,
        positionFrom: biggestPositionJump.first,
        positionTo: biggestPositionJump.last,
        confidence: confidenceLabel(biggestPositionJump.impressions, biggestPositionJump.changePercent),
        score: 100 + biggestPositionJump.jump * 5,
      });
    }

    if (candidates.length === 0) return null;
    return [...candidates].sort((a, b) => b.score - a.score)[0];
  }, [queriesRows, newQueriesRows, querySparklines]);

  const handleShare = async () => {
    if (!bestWin) return;
    const image = makeShareImage(siteName, bestWin);
    if (!image) return;
    const blob = await (await fetch(image)).blob();
    const file = new File([blob], "seo-win.png", { type: "image/png" });

    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({
        title: "SEO Win",
        text: `${bestWin.query} improved for ${siteName}`,
        files: [file],
      });
      return;
    }

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "seo-win.png";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardCard
      title="SEO Win"
      subtitle={bestWin ? bestWin.reason : "No ranking signals detected in this range"}
      action={
        bestWin ? (
          <span className="rounded-full border border-border px-2 py-0.5 text-[11px] text-muted-foreground">
            Confidence: {bestWin.confidence}
          </span>
        ) : null
      }
      footer={
        bestWin ? (
          <button
            type="button"
            onClick={handleShare}
            className="rounded border border-input bg-background px-3 py-1.5 text-xs font-medium text-foreground hover:bg-accent"
          >
            Share win
          </button>
        ) : null
      }
      className="min-h-[180px]"
    >
      <div className="px-5 py-4">
        {bestWin ? (
          <div className="space-y-1.5 text-sm">
            <p className="text-foreground truncate" title={bestWin.query}>
              "{bestWin.query}"
            </p>
            {bestWin.positionFrom != null && bestWin.positionTo != null && (
              <p className="text-muted-foreground">
                Position {bestWin.positionFrom.toFixed(1)} → {bestWin.positionTo.toFixed(1)}
              </p>
            )}
            <p className="text-positive font-medium">
              {bestWin.clicksGrowth >= 0 ? "+" : ""}
              {bestWin.clicksGrowth}% clicks in the selected period
            </p>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">No ranking signals detected in this range.</p>
        )}
      </div>
    </DashboardCard>
  );
}

